<div class="paynow-confirm-blik">
    <img src="<?php echo WC_PAY_BY_PAYNOW_PL_PLUGIN_ASSETS_PATH . 'images/blik-confirm.png'; ?>"
         alt="<?php echo __( 'Confirm the payment using the app on your phone.', 'pay-by-paynow-pl' ); ?>">
</div>
<script>
	<?php
	$order_id = filter_input( INPUT_GET, 'orderId' );
	$token = filter_input( INPUT_GET, 'token' );
	if ($order_id && $token) {
	wp_enqueue_script( 'paynow-confirm-blik', WC_PAY_BY_PAYNOW_PL_PLUGIN_ASSETS_PATH . 'js/confirm-blik.js', array( 'jquery' ), wc_pay_by_paynow_pl_plugin_version() );
	$order = wc_get_order( $order_id );
	?>
    var paynow_status_rest_api = '<?php echo WC_Gateway_Pay_By_Paynow_PL_Status_Handler::get_rest_api_status_url() . '?' . http_build_query( array(
			'orderId' => $order_id,
			'token'   => $token
		) );?>';
    var paynow_order_confirmed = '<?php echo $order->get_checkout_order_received_url();?>'
	<?php } ?>
</script>