<div class="paynow-leaselink alignwide <?php echo $data['class']; ?>">
    <div class="paynow-leaselink__button" data-leaselink-widget-button>
        <?php if (wc_pay_by_paynow()->settings()->get_leaselink_show_rate()): ?>
            <p class="paynow-leaselink__title">WEŹ LEASING OD <?php echo wc_price($data['widget_net_value']) ?></p>
        <?php else: ?>
            <p class="paynow-leaselink__title">WEŹ LEASING TERAZ</p>
        <?php endif; ?>
        <div class="paynow-leaselink__image-container">
            <img
                class="paynow-leaselink__image"
                src="<?php echo WC_PAY_BY_PAYNOW_PL_PLUGIN_ASSETS_PATH . 'images/' . $data['image']; ?>"
                alt="Arrow"
            >
        </div>
    </div>
</div>

<div class="paynow-leaselink__calculator__background paynow-leaselink__calculator__hidden" data-leaselink-calculator>
    <div class="paynow-leaselink__calculator" data-products="<?php echo $data['product_ids'] ?>">
        <div class="paynow-leaselink__calculator__header">
            <img class="paynow-leaselink__calculator__header__logo" src="<?php echo WC_PAY_BY_PAYNOW_PL_PLUGIN_ASSETS_PATH . 'images/ll-logo.svg'; ?>" alt="ll logo">
            <p>Leasing i raty dla firm 24/7</p>
            <div class="paynow-leaselink__calculator__header__exit-wrapper" data-leaselink-calculator-close>
                <img class="paynow-leaselink__calculator__header__exit" src="<?php echo WC_PAY_BY_PAYNOW_PL_PLUGIN_ASSETS_PATH . 'images/exit.svg'; ?>" alt="exit icon">
            </div>
        </div>

        <div class="paynow-leaselink__calculator__products">
            <p class="paynow-leaselink__calculator__products__title">Wybrane produkty</p>
            <div class="paynow-leaselink__calculator__products__product-wrapper">
                <?php foreach ($data['widget_products'] ?? [] as $product): ?>
                    <div class="paynow-leaselink__calculator__products__product">
                        <p class="paynow-leaselink__calculator__products__product__qty">1 x</p>
                        <p class="paynow-leaselink__calculator__products__product__text">
                            <span class="paynow-leaselink__calculator__products__product__title"><?php echo $product->get_title(); ?></span>
                            <br class="paynow-leaselink__calculator__products__product__title-break"/>
                            <span class="paynow-leaselink__calculator__products__product__price"><?php echo wc_price(wc_get_price_excluding_tax($product)); ?> (netto)</span>
                        </p>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="paynow-leaselink__calculator__products-summary-lg">
                <p class="paynow-leaselink__calculator__products-summary-lg__label">Razem (netto):</p>
                <p class="paynow-leaselink__calculator__products-summary-lg__price"><?php echo wc_price($data['widget_products_sum']); ?></p>
            </div>
        </div>

        <div class="paynow-leaselink__calculator__products-summary">
            <p class="paynow-leaselink__calculator__products-summary__label">Razem (netto):</p>
            <p class="paynow-leaselink__calculator__products-summary__price"><?php echo wc_price($data['widget_products_sum']); ?></p>
        </div>

        <div class="paynow-leaselink__calculator__copy-lg">
            <p>Przedstawione kalkulacje nie stanowią oferty w rozumieniu kodeksu cywilnego.</p>
        </div>

        <div class="paynow-leaselink__calculator__config">
            <div class="paynow-leaselink__calculator__config__form">
                <p class="paynow-leaselink__calculator__config__title">Ile rat wybierasz?</p>
                <div class="paynow-leaselink__calculator__config__buttons-wrapper">
                    <?php foreach ($data['rates'] ?? [] as $key => $rate): ?>
                        <div>
                            <input class="paynow-leaselink__calculator__config__input" type="radio" id="rates-<?php echo $rate; ?>" name="rates" value="<?php echo $rate; ?>" <?php echo ($rate === $data['checked_rate'] ? 'checked' : ''); ?>>
                            <label class="paynow-leaselink__calculator__config__label" for="rates-<?php echo $rate; ?>"><?php echo $rate; ?></label>
                        </div>
                    <?php endforeach; ?>
                </div>

                <p class="paynow-leaselink__calculator__config__title">Jaką kwotę chcesz wpłacić na początek?</p>
                <div class="paynow-leaselink__calculator__config__buttons-wrapper">
                    <?php foreach ($data['entry_payment'] ?? [] as $key => $entry_payment): ?>
                        <div>
                            <input class="paynow-leaselink__calculator__config__input" type="radio" id="entry-payment-<?php echo $entry_payment; ?>" name="entry-payment" value="<?php echo $entry_payment; ?>" <?php echo ($key === 0 ? 'checked' : ''); ?>>
                            <label class="paynow-leaselink__calculator__config__label" for="entry-payment-<?php echo $entry_payment; ?>"><?php echo $entry_payment; ?>%</label>
                        </div>
                    <?php endforeach; ?>
                </div>

                <p class="paynow-leaselink__calculator__config__title">Jaką wysokość wykupu wybierasz?</p>
                <div class="paynow-leaselink__calculator__config__buttons-wrapper">
                    <?php foreach ($data['closing_payment'] ?? [] as $key => $closing_payment): ?>
                        <div>
                            <input class="paynow-leaselink__calculator__config__input" type="radio" id="closing-payment-<?php echo $closing_payment; ?>" name="closing-payment" value="<?php echo $closing_payment; ?>" <?php echo ($key === 0 ? 'checked' : ''); ?>>
                            <label class="paynow-leaselink__calculator__config__label" for="closing-payment-<?php echo $closing_payment; ?>"><?php echo $closing_payment; ?>%</label>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <hr class="paynow-leaselink__calculator__config__hr" />

            <div class="paynow-leaselink__calculator__config__summary">
                <div class="paynow-leaselink__calculator__config__summary__box">
                    <p class="paynow-leaselink__calculator__config__summary__title">Opłata początkowa:</p>
                    <p class="paynow-leaselink__calculator__config__summary__value" data-entry-netto-payment><?php echo wc_price($data['entry_net_payment']); ?> (netto)</p>
                </div>

                <div class="paynow-leaselink__calculator__config__summary__box">
                    <p class="paynow-leaselink__calculator__config__summary__title">Wykup:</p>
                    <p class="paynow-leaselink__calculator__config__summary__value" data-closing-netto-payment><?php echo wc_price($data['closing_net_payment']); ?> (netto)</p>
                </div>

                <div>
                    <p class="paynow-leaselink__calculator__config__summary__title">Produkt finansowy:</p>
                    <p class="paynow-leaselink__calculator__config__summary__value" data-financial-product-name><?php echo $data['financial_product_name']; ?></p>
                </div>
            </div>
        </div>

        <div class="paynow-leaselink__calculator__copy">
            <p>Przedstawione kalkulacje nie stanowią<br/>oferty w rozumieniu kodeksu cywilnego.</p>
        </div>

        <div class="paynow-leaselink__calculator__instruction">
            <h4 class="paynow-leaselink__calculator__instruction__title">Jak skorzystać?</h4>
            <ol class="paynow-leaselink__calculator__instruction__list">
                <li class="paynow-leaselink__calculator__instruction__list__item">Dodaj produkty do koszyka.</li>
                <li class="paynow-leaselink__calculator__instruction__list__item">Wybierz LeaseLink jako metodę płatności.</li>
                <li class="paynow-leaselink__calculator__instruction__list__item">Złóż zamówienie, a przejdziesz na stronę leaselink.pl.</li>
                <li class="paynow-leaselink__calculator__instruction__list__item">Podaj swoje podstawowe dane.</li>
                <li class="paynow-leaselink__calculator__instruction__list__item">Decyzję poznasz po 2 minutach i zdalnie podpiszesz prostą umowę.</li>
            </ol>
        </div>

        <div class="paynow-leaselink__calculator__rating">
            <img class="paynow-leaselink__calculator__rating__image" src="<?php echo WC_PAY_BY_PAYNOW_PL_PLUGIN_ASSETS_PATH . 'images/widget-ratings.svg'; ?>" alt="widget ratings">
            <img class="paynow-leaselink__calculator__rating__image-lg" src="<?php echo WC_PAY_BY_PAYNOW_PL_PLUGIN_ASSETS_PATH . 'images/widget-ratings-lg.svg'; ?>" alt="widget ratings">
        </div>

        <div class="paynow-leaselink__calculator__summary">
            <div>
                <div class="paynow-leaselink__calculator__summary__button-wrapper" data-leaselink-calculator-close>
                    <div class="paynow-leaselink__calculator__summary__arrow-wrapper">
                        <img
                            class="paynow-leaselink__calculator__summary__arrow"
                            src="<?php echo WC_PAY_BY_PAYNOW_PL_PLUGIN_ASSETS_PATH . 'images/arrow-purple.svg'; ?>"
                            alt="Arrow"
                        >
                    </div>
                    <button type="button" class="paynow-leaselink__calculator__summary__button">WRÓĆ DO SKLEPU</button>
                </div>
            </div>
            <div>
                <p class="paynow-leaselink__calculator__summary__label">Miesięcznie (netto):</p>
                <p class="paynow-leaselink__calculator__summary__price" data-monthly-netto-payment><?php echo wc_price($data['widget_net_value']) ?></p>
            </div>
        </div>
    </div>
</div>
